---
- hosts: all
  tasks:
    - name: Install DHCP Server
      script: script.ps1 

    - name: Update DHCP Installation Status
      ansible.windows.win_regedit:
        path: HKLM:\Software\Microsoft\ServerManager\Roles
        name: 12
        data: 2
