---
- name: Configure DHCP and DNS settings on a Windows server
  hosts: all
  gather_facts: no
  tasks:
    - name: Install DHCP Role
      ansible.windows.win_powershell:
        script: |
          Install-WindowsFeature DHCP -IncludeManagementTools
          netsh dhcp add securitygroups
          Restart-Service dhcpserver

    - name: Add DHCP Server in Active Directory
      ansible.windows.win_powershell:
        script: |
          Add-DhcpServerInDC -DnsName "DC1.ad.local" -IPAddress "192.168.101.177"

    - name: Set DHCP Server v4 DNS Settings
      ansible.windows.win_powershell:
        script: |
          Set-DhcpServerv4DnsSetting -ComputerName "DC1.ad.local" -DynamicUpdates "Always" -DeleteDnsRRonLeaseExpiry $True

    - name: Add DHCP Scope and Exclusion Range
      ansible.windows.win_powershell:
        script: |
          Add-DhcpServerv4Scope -name "Corpnet" -StartRange "192.168.101.1" -EndRange "192.168.101.254" -SubnetMask "255.255.255.0" -State Active
          Add-DhcpServerv4ExclusionRange -ScopeID "192.168.101.0" -StartRange "192.168.101.1" -EndRange "192.168.101.15"

    - name: Set DHCP Option for Default Gateway
      ansible.windows.win_powershell:
        script: |
          Set-DhcpServerv4OptionValue -OptionID 3 -Value "192.168.101.1" -ScopeID "192.168.101.0" -ComputerName "DC1.ad.local"

    - name: Set DHCP Options for DNS
      ansible.windows.win_powershell:
        script: |
          Set-DhcpServerv4OptionValue -DnsDomain "ad.local" -DnsServer "192.168.101.177"
